---
- name: "copy build file"
  hosts: all
  become: true
  
  tasks:
  - name: install java
    yum:
      name: java
      state: latest
  - name: build war
    ansible.builtin.copy:
      src: ./webapp/target/webapp.war
      dest: /opt/tomcat/webapps
