---
- name: "copy build file"
  hosts: all
  become: true
  
  tasks:
  - name: install java
    yum:
      name: java
      state: latest
  - name: build war
    ansible.builtin.copy:
      src: /var/lib/jenkins/workspace/pipeline_job/webapp/target/*.war
      dest: /opt/tomcat/webapps
      remote_src: yes
