---
- name: "copy build file"
  hosts: all
  become: true
  
  tasks:
  - name: install java
    yum:
      name: java
      state: latest
  - name: download tomcat package
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /opt/
  - name: unarchive package
    ansible.builtin.unarchive:
      src: /opt/apache-tomcat-9.0.54.tar.gz
      dest: /opt/
      remote_src: yes
  - name: remove a file
    ansible.builtin.file: 
       path: /opt/apache-tomcat-9.0.54.tar.gz
       state: absent
  - name: build war
    ansible.builtin.copy:
      src: ./webapp/target/webapp.war 
      dest: /opt/apache-tomcat-9.0.54/webapps
  - name: restart service
    ansible.builtin.shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh
     
