---
- name: pid of tomcat
  hosts: all
  become: true
  
  tasks:
  - name: Ansible find file examples
    find:
      paths: /opt
      patterns: "startup.sh"
      register: files_matched 
  - name: Getting process IDs of the process
    community.general.pids:
      msg: "PIDS of tomcat:{{pids_of_tomcat.pids|join(',')}}"
